#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
import time
from enum import IntEnum
from pandas import Timestamp, Timedelta
from dataclasses import dataclass, field
from typing import Any, List, Tuple, Dict, Set
from typing import Iterable, Callable, ClassVar
from src.models import Account, AccountDict, Rules
from src.models import Quote, Candle, Tick, QuoteDict
from src.models import OrderReject, Order, Trade
from src.models import OrderModify, OrderDelete
from src.models import SymbolDict, TimeFrame
from src.models import StreamingAgent
from src.models import LOG_RESPONSES
from src.utils import Redis, b64
from src.utils import Log, TZ

#███████████████████████████████████████████████████████████████████████████████████████████████
#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#▄▄▄▄▄▄▄▄▄▄▄
@dataclass#█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
class ExecReceiver(StreamingAgent):
    id: str = field(init = True, default = None)
    accounts: AccountDict = field(init = True)
    rules: Rules = field(init = True, default = None)
    timeframes: Set[str] = field(init = True)
    symbols: SymbolDict = field(init = True)
    STREAM_PREFIX: ClassVar[str] = "BTX-"
    STREAM_MIDFIX: ClassVar[str] = "EXEC"
    DEFAULT_LEVERAGE: ClassVar[float] = 100
    DEFAULT_BALANCE: ClassVar[float] = 10000
    XGROUP: ClassVar[str] = Redis.Group.EXEC
    VERBOSE_WRONG_BTID: ClassVar[str] = "Wrong BTID: \"{btid} != {id}\""
    VERBOSE_NO_BTID: ClassVar[str] = "Autogenerated BTID \"{id}\" (not recommended for prod)"
    VERBOSE_NO_SYMBOL: ClassVar[str] = "\"{symbol}\" in {obj} not found in symbol database during init"

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def __post_init__(self):

        if (self.id is None):
            self.id = b64()
            Log.warning(self.VERBOSE_NO_BTID.format(id = self.id))
        self.stream_prefix = self.STREAM_PREFIX + self.id
        self.time = Timestamp.min.tz_localize(TZ)
        if (self.accounts is None): self.accounts = {self.id: Account(
            id = self.id, time = self.time, venue = self.STREAM_PREFIX,
            balance = self.DEFAULT_BALANCE, leverage = self.DEFAULT_LEVERAGE)}
        self._timeframes = set()
        self._tick_driven = False
        for tf in self.timeframes:
            if (tf == "T1"): self._tick_driven = True
            else: self._timeframes.add(TimeFrame[tf])
        self._min_tf: TimeFrame = min(self._timeframes)
        self.callbacks: dict[Order.Action, Callable] = {
            Order.Action.CREATE: self.order_create,
            Order.Action.MODIFY: self.order_modify,
            Order.Action.DELETE: self.order_delete,
        }
        super().__post_init__()
        self._procs[f"ExecReceiver/main"] = self.main

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    async def main(self):

        self.quotes: QuoteDict = dict.fromkeys(self.symbols)
        self.orders, self.trades = dict[str, Order](), dict[str, Trade]()
        for account in self.accounts.values():
            for symbol_key, orders in account.orders_active.items():
                if (symbol_key not in self.symbols): raise KeyError(
                    self.VERBOSE_NO_SYMBOL.format(obj = "orders",
                        symbol = str.join(" ", symbol_key)))
                self.orders.update(orders)
            for symbol_key, trades in account.trades_active.items():
                if (symbol_key not in self.symbols): raise KeyError(
                    self.VERBOSE_NO_SYMBOL.format(obj = "trades",
                        symbol = str.join(" ", symbol_key)))
                if not account.is_hedging:
                    trade = trades["NETTING"]
                    self.trades[trade.UID] = trade
                else: self.trades.update(trades)
            for symbol_key in self.symbols:
                if (symbol_key not in account.orders_active):
                    account.orders_active[symbol_key] = dict()
                if (symbol_key not in account.trades_active):
                    account.trades_active[symbol_key] = dict()
                    if not account.is_hedging:
                        account.trades_active["NETTING"] = None
                if (symbol_key not in account.orders_closed):
                    account.orders_closed[symbol_key] = dict()
                if (symbol_key not in account.trades_closed):
                    account.trades_closed[symbol_key] = dict()

        listen_to = set()
        for symbol in self.symbols.values():
            head = [self.stream_prefix, "DATA", symbol.venue, symbol.symbol]
            for tf in self.timeframes: listen_to.add(Redis.join(*head, tf))
        for account in self.accounts.values():
            head = [self.stream_prefix, "EXEC", account.venue, account.id]
            listen_to.add(Redis.join(*head, Order.Action.CREATE.value))
            listen_to.add(Redis.join(*head, Order.Action.MODIFY.value))
            listen_to.add(Redis.join(*head, Order.Action.DELETE.value))
        await Redis.consume(self.process, src = self, xstreams = listen_to, n = 0)

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    async def process(self, stream: str, message_id: str, payload: dict):

        btid, source, stream = stream.split(Redis.SEP, maxsplit = 3)
        if (btid != self.id): return Log.error(
            self.VERBOSE_WRONG_BTID.format(btid = btid, id = self.id))
        payload["time"] = Redis.id_to_timestamp(message_id)
        responses = None
        if (source == "DATA"):
            responses = self.on_quote(stream, payload)
        elif (source == "EXEC"):
            *account_key, action_str = stream.split(Redis.SEP)
            callback = self.callbacks[Order.ACTION[action_str]]
            payload.update(account_key = account_key)
            responses = callback(**payload)
        if responses: await self.send_responses(responses)

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def on_quote(self, stream: str, payload: dict):

        venue_name, symbol_name, tf = stream.split(Redis.SEP)[2 :]
        symbol_key = (venue_name, symbol_name)
        try: payload["symbol"] = self.symbols[symbol_key]
        except Exception as EXC: return Log.exception(EXC)
        if (self._tick_driven and (tf == "T1")): obj = Tick(**payload)
        elif (tf == self._min_tf.name):
            obj = Candle(tf = TimeFrame[tf], **payload)
            if (obj.ob is None) or (obj.ob == obj.oa): obj.ob = obj.oa - self.rules.fixed_spread
            if (obj.hb is None) or (obj.hb == obj.ha): obj.hb = obj.ha + self.rules.fixed_spread
            if (obj.lb is None) or (obj.lb == obj.la): obj.lb = obj.la - self.rules.fixed_spread
            if (obj.cb is None) or (obj.cb == obj.ca): obj.cb = obj.ca + self.rules.fixed_spread
        else: return
        self.time = obj.time_event
        self.quotes[symbol_key] = obj
        return [*self.order_clearing(*symbol_key),
                *self.trade_clearing(*symbol_key)]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_clearing(self, venue: str, symbol: str):

        symbol_key = (venue, symbol)
        quote: Quote = self.quotes[symbol_key]
        stuff_rejected = dict[str, OrderReject]()
        orders_cleared = dict[str, Order]()
        for account in self.accounts.values():
            for UID in sorted(account.orders_active[symbol_key]):
                order: Order = account.orders_active[symbol_key][UID]
                result = account.on_order_filled(order, self.rules, quote)
                if isinstance(result, OrderReject): stuff_rejected[UID] = result
                elif (result is None): continue
                orders_cleared[order.UID] = order
                self.orders.pop(order.UID)
        return [*stuff_rejected.values(),
                *orders_cleared.values()]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def trade_clearing(self, venue: str, symbol: str):

        symbol_key = (venue, symbol)
        quote: Quote = self.quotes[symbol_key]
        stuff_rejected = dict[str, OrderReject]()
        trades_cleared = dict[str, Trade]()
        for account in self.accounts.values():
            for UID in sorted(account.trades_active[symbol_key]):
                trade: Trade = account.trades_active[symbol_key][UID]
                result = account.on_trade_closed(trade, self.rules, quote)
                if isinstance(result, OrderReject): stuff_rejected[UID] = result
                elif (result is None): continue
                trades_cleared[trade.UID] = trade
                self.trades.pop(trade.UID)
        return [*stuff_rejected.values(),
                *trades_cleared.values()]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_create(self, account_key: Tuple[str, str], **payload):

        venue_name = payload.pop("venue", None)
        symbol_name = payload.pop("symbol", None)
        symbol_key = (venue_name, symbol_name)
        symbol_str = str.join(" ", symbol_key)
        symbol = self.symbols.get(symbol_key, None)
        quote = self.quotes.get(symbol_key, None)
        if (symbol is None) or (quote is None):
            reason = OrderReject.Reason.UNKNOWN_SYMBOL
            message = reason.value.format(subject = "OrderCreate", 
                symbol = symbol_str,summary = payload.get("UID", None))
            response = OrderReject(account = self.account, **payload,
                reason = reason, message = message, time = self.time)
        else:
            quote = self.quotes[symbol_key]
            account = self.accounts[account_key]
            request = Order.create(account, symbol = symbol, **payload)
            response = account.on_order_create(request, self.rules, quote)
        return [response]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def check_order_exists(self, account_key: Tuple[str, str], RequestType: type, **kwargs):

        subject = RequestType.__name__
        account = self.accounts[account_key]
        if (UID := kwargs.pop("UID", None)):
            if (UID in self.orders): return self.orders[UID]
            if (UID in self.trades): return self.trades[UID]
        reason = OrderReject.Reason.UNKNOWN_UID
        message: str = reason.value.format(
            subject = subject, summary = "#" + UID)
        return OrderReject(account = account, time = self.time,
                UID = UID, reason = reason, message = message)

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_modify(self, account_key: Tuple[str, str], **payload):

        obj = self.check_order_exists(account_key, OrderModify, **payload)
        if isinstance(obj, OrderReject): return [obj]
        quote: Quote = self.quotes[(obj.symbol.venue, obj.symbol.symbol)]
        request = OrderModify(account = self.accounts[account_key], **payload)
        response = self.accounts[account_key].on_order_modify(request, quote)
        return [response]
        
    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_delete(self, account_key: Tuple[str, str], **payload):

        obj = self.check_order_exists(account_key, OrderDelete, **payload)
        if isinstance(obj, OrderReject): return [obj]
        quote: Quote = self.quotes[(obj.symbol.venue, obj.symbol.symbol)]
        request = OrderDelete(account = self.accounts[account_key], **payload)
        response = self.accounts[account_key].on_order_delete(request, quote)
        return [response]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    @Redis.stream#█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    async def send_responses(self, *responses):

        async for response in responses:
            log_resp = LOG_RESPONSES.get(
                type(response), Log.debug)
            log_resp(response)
            yield response
        async for account in self.accounts.values():
            yield account


#███████████████████████████████████████████████████████████████████████████████████████████████
#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#▄▄▄▄▄▄▄▄▄▄▄
@dataclass#█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
class TestExecReceiver(ExecReceiver):
    pass