#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
import asyncio
from collections import deque
from dataclasses import dataclass, field
from typing import Any, List, Tuple, Dict, Set
from typing import Iterable, Callable, ClassVar
from pandas import Series, DataFrame, Timestamp
from src.models import Account, AccountDict, Rules
from src.models import Quote, Candle, Tick, QuoteDict
from src.models import OrderCreate, OrderModify, OrderDelete
from src.models import Reject, Order, Trade
from src.models import SymbolDict, TimeFrame
from src.models import StreamingAgent
from src.models import LOG_RESPONSES
from src.utils import b64, Log, Redis, TZ, _FOLDER_LOG
from .datareader import FileReader, TSDBReader

#███████████████████████████████████████████████████████████████████████████████████████████████
#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#▄▄▄▄▄▄▄▄▄▄▄
@dataclass#█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
class Simulator(StreamingAgent):
    id: str = field(init = True, default = None)
    accounts: AccountDict = field(init = True)
    rules: Rules = field(init = True, default = None)
    symbols: SymbolDict = field(init = True)
    timeframes: Set[str] = field(init = True)
    time_since: Timestamp = field(init = True, default = None)
    time_until: Timestamp = field(init = True, default = None)
    reader_mode: str = field(init = True, default = "tsdb")
    wait_response: bool = field(init = True, default = True)
    STREAM_PREFIX: ClassVar[str] = "BTX-"
    DEFAULT_LEVERAGE: ClassVar[float] = 100
    DEFAULT_BALANCE: ClassVar[float] = 10000
    XGROUP: ClassVar[str] = Redis.Group.EXEC
    VERBOSE_WRONG_BTID: ClassVar[str] = "Wrong BTID: \"{0} != {1}\""
    VERBOSE_NO_BTID: ClassVar[str] = "Autogenerated BTID \"{id}\" (not recommended for prod)"
    VERBOSE_NO_SYMBOL: ClassVar[str] = "\"{symbol}\" in {obj} not found in symbol database during init"
    VERBOSE_NO_HAND: ClassVar[str] = "No handshake from \"{0}\""
    VERBOSE_UNPHASED: ClassVar[str] = "Unphased item: {0} != {1}"
    TS_SINCE_DEF: ClassVar[Timestamp] = Timestamp.min.tz_localize(TZ)
    TS_UNTIL_DEF: ClassVar[Timestamp] = Timestamp.max.tz_localize(TZ)
    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def __post_init__(self):
        if (self.id is None):
            self.id = b64()
            Log.warning(self.VERBOSE_NO_BTID.format(id = self.id))
        self.stream_prefix = self.STREAM_PREFIX + self.id
        if (self.accounts is None): self.accounts = {self.id: Account(
            id = self.id, time = self.time, venue = self.STREAM_PREFIX,
            balance = self.DEFAULT_BALANCE, leverage = self.DEFAULT_LEVERAGE)}
        self._timeframes = set()
        self._tick_driven = False
        for tf in self.timeframes:
            if (tf == "T1"): self._tick_driven = True
            else: self._timeframes.add(TimeFrame[tf])
        self._min_tf: TimeFrame = min(self._timeframes)
        self.callbacks: dict[Order.Action, Callable] = {
            Order.Action.CREATE: self.order_create,
            Order.Action.MODIFY: self.order_modify,
            Order.Action.DELETE: self.order_delete,
        }
        self.account_hist = deque()
        self.time = Timestamp.min.tz_localize(TZ)
        self.reader_mode = self.reader_mode.upper()
        if (self.time_since is None): self.time_since = self.TS_SINCE_DEF
        if (self.time_until is None): self.time_until = self.TS_UNTIL_DEF
        if (self.time_since.tz is None): self.time_since = self.time_since.tz_localize(TZ)
        if (self.time_until.tz is None): self.time_until = self.time_until.tz_localize(TZ)
        args = {"timeframes": self.timeframes, "symbols": self.symbols,
            "time_since": self.time_since, "time_until": self.time_until}
        if (self.reader_mode == "FILE"): self.reader = FileReader(**args)
        elif (self.reader_mode == "TSDB"): self.reader = TSDBReader(**args)
        else: raise ValueError(f"Wrong reader mode: \"{self.reader_mode}\"")
        self._release_quote = asyncio.Event()
        super().__post_init__()
        name = self.__class__.__name__
        self._procs[name + "/datafeed"] = self.datafeed
        self._procs[name + "/exchange"] = self.exchange

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    async def exchange(self):

        self.orders = dict[str, Order]()
        self.trades = dict[str, Trade]()
        self.quotes: QuoteDict = dict.fromkeys(self.symbols)
        for account in self.accounts.values():
            for symbol_key, orders in account.orders_active.items():
                if (symbol_key not in self.symbols): raise KeyError(
                    self.VERBOSE_NO_SYMBOL.format(obj = "orders",
                        symbol = str.join(" ", symbol_key)))
                self.orders.update(orders)

            for symbol_key, trades in account.trades_active.items():
                if (symbol_key not in self.symbols): raise KeyError(
                    self.VERBOSE_NO_SYMBOL.format(obj = "trades",
                        symbol = str.join(" ", symbol_key)))
                if not account.is_hedging:
                    trade = trades["NETTING"]
                    self.trades[trade.UID] = trade
                else: self.trades.update(trades)

            for symbol_key in self.symbols:
                if (symbol_key not in account.orders_active):
                    account.orders_active[symbol_key] = dict()
                if (symbol_key not in account.trades_active):
                    account.trades_active[symbol_key] = dict()
                    if not account.is_hedging:
                        account.trades_active["NETTING"] = None
                if (symbol_key not in account.orders_closed):
                    account.orders_closed[symbol_key] = dict()
                if (symbol_key not in account.trades_closed):
                    account.trades_closed[symbol_key] = dict()

        listen_to = {Redis.join(self.stream_prefix, "HAND")}
        for account in self.accounts.values():
            kw = {"venue": account.venue, "id": account.id}
            listen_to.add(Redis.join(self.stream_prefix, OrderCreate.stream_key(**kw)))
            listen_to.add(Redis.join(self.stream_prefix, OrderModify.stream_key(**kw)))
            listen_to.add(Redis.join(self.stream_prefix, OrderDelete.stream_key(**kw)))
        await Redis.consume(self.on_message, src = self, xstreams = listen_to, n = 0)

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    async def on_message(self, stream: str, mid: str, payload: dict):
        
        account: Account = None
        responses = list[Order | Trade | Reject]()
        prefix, source, stream = stream.split(Redis.SEP, maxsplit = 3)
        payload["time"] = Redis.id_to_timestamp(mid)
        if (prefix != self.stream_prefix): return Log.error(
            self.VERBOSE_WRONG_BTID.format(prefix, self.stream_prefix))
        if (source == "HAND") and self.wait_response:
            mid = payload.pop("hsid", "NO_HSID")
            if (mid == self.hsid): return self._release_quote.set()
            Log.error(self.VERBOSE_UNPHASED.format(mid, self.hsid))
            return
        if (source == "EXEC"):
            *account_key, action_str = stream.split(Redis.SEP)
            callback = self.callbacks[Order.ACTION[action_str]]
            payload.update(account_key = account_key)
            responses = callback(**payload)
        
        async for response in responses:
            log_resp = LOG_RESPONSES.get(type(response), Log.debug)
            log_resp(response)
            yield response

        async for account in self.accounts.values():
            yield account
            if responses:
                payload = account.payload
                payload["time"] = self.time
                payload["account"] = account.id
                self.account_hist.append(payload)

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_create(self, account_key: Tuple[str, str], **payload):

        venue_name = payload.pop("venue", None)
        symbol_name = payload.pop("symbol", None)
        symbol_key = (venue_name, symbol_name)
        symbol_str = str.join(" ", symbol_key)
        symbol = self.symbols.get(symbol_key, None)
        quote = self.quotes.get(symbol_key, None)
        account = self.accounts[account_key]
        if (symbol is None) or (quote is None):
            reason = Reject.Reason.UNKNOWN_SYMBOL
            message = reason.value.format(subject = "OrderCreate", 
                symbol = symbol_str,summary = payload.get("UID", None))
            response = Reject(account = account, **payload,
                reason = reason, message = message, time = self.time)
        else:
            quote = self.quotes[symbol_key]
            request = Order.create(account, symbol = symbol, **payload)
            response = account.on_order_create(request, self.rules, quote)
        return [response]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def check_order_exists(self, account_key: Tuple[str, str], RequestType: type, **kwargs):

        subject = RequestType.__name__
        account = self.accounts[account_key]
        if (UID := kwargs.pop("UID", None)):
            if (UID in self.orders): return self.orders[UID]
            if (UID in self.trades): return self.trades[UID]
        reason = Reject.Reason.UNKNOWN_UID
        message: str = reason.value.format(
            subject = subject, summary = "#" + UID)
        return Reject(account = account, time = self.time,
                UID = UID, reason = reason, message = message)

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_modify(self, account_key: Tuple[str, str], **payload):

        obj = self.check_order_exists(account_key, OrderModify, **payload)
        if isinstance(obj, Reject): return [obj]
        quote: Quote = self.quotes[(obj.symbol.venue, obj.symbol.symbol)]
        request = OrderModify(account = self.accounts[account_key], **payload)
        response = self.accounts[account_key].on_order_modify(request, quote)
        return [response]
        
    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_delete(self, account_key: Tuple[str, str], **payload):

        obj = self.check_order_exists(account_key, OrderDelete, **payload)
        if isinstance(obj, Reject): return [obj]
        quote: Quote = self.quotes[(obj.symbol.venue, obj.symbol.symbol)]
        request = OrderDelete(account = self.accounts[account_key], **payload)
        response = self.accounts[account_key].on_order_delete(request, quote)
        return [response]

#███████████████████████████████████████████████████████████████████████████████████████████████
#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    @Redis.stream#█▄▄▄▄▄▄▄▄▄
    async def datafeed(self):
        last_time_us: int = 0
        queue = deque[Tick | Candle]()
        async for item in self.reader:
            self.time = item.time_event
            responses = self.on_quote(item)
            async for resp in responses: yield resp
            if not item.INTERVAL_BASED: yield item
            else:
                if (last_time_us < item.time_us):
                    last_time_us = item.time_us
                    while len(queue):
                        prev_item = queue.pop()
                        prev_item.rem = len(queue)
                        yield prev_item

                queue.appendleft(item)

            self.hsid = item.time_b64
            last_time_us = item.time_us
            if not self.wait_response: continue
            await self._release_quote.wait()
            self._release_quote.clear()

        self.active = False
        self.finish()

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def on_quote(self, item: Tick | Candle):

        spread = self.rules.fixed_spread
        symbol_key = (item.symbol.venue, item.symbol.symbol)
        if isinstance(item, Candle) and (spread is not None):
            if not item.ob or (item.ob == item.oa): item.ob = item.oa - spread
            if not item.hb or (item.hb == item.ha): item.hb = item.ha + spread
            if not item.lb or (item.lb == item.la): item.lb = item.la - spread
            if not item.cb or (item.cb == item.ca): item.cb = item.ca + spread
        elif isinstance(item, Tick) and (spread is not None):
            if not item.pb or (item.pb == item.pa): item.pb = item.pa - spread
        self.quotes[symbol_key] = item
        return [*self.order_clearing(*symbol_key),
                *self.trade_clearing(*symbol_key)]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def order_clearing(self, venue: str, symbol: str):

        symbol_key = (venue, symbol)
        quote: Quote = self.quotes[symbol_key]
        stuff_rejected = dict[str, Reject]()
        orders_cleared = dict[str, Order]()
        for account in self.accounts.values():
            for UID in sorted(account.orders_active[symbol_key]):
                order: Order = account.orders_active[symbol_key][UID]
                result = account.on_order_filled(order, self.rules, quote)
                if isinstance(result, Reject): stuff_rejected[UID] = result
                elif (result is None): continue
                orders_cleared[order.UID] = order
                self.orders.pop(order.UID)
        return [*stuff_rejected.values(),
                *orders_cleared.values()]

    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def trade_clearing(self, venue: str, symbol: str):

        symbol_key = (venue, symbol)
        quote: Quote = self.quotes[symbol_key]
        stuff_rejected = dict[str, Reject]()
        trades_cleared = dict[str, Trade]()
        for account in self.accounts.values():
            for UID in sorted(account.trades_active[symbol_key]):
                trade: Trade = account.trades_active[symbol_key][UID]
                result = account.on_trade_closed(trade, self.rules, quote)
                if isinstance(result, Reject): stuff_rejected[UID] = result
                elif (result is None): continue
                trades_cleared[trade.UID] = trade
                self.trades.pop(trade.UID)
        return [*stuff_rejected.values(),
                *trades_cleared.values()]

#███████████████████████████████████████████████████████████████████████████████████████████████
#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
    #▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    def finish(self):
        df_orders = dict[str, dict]()
        df_trades = dict[str, dict]()
        for account in self.accounts.values():
            for orders in account.orders_closed.values():
                for (venue, symbol), order in orders.items():
                    payload = order.payload
                    payload.update(venue = venue, symbol = symbol, account = account.id)
                    df_orders[order.UID] = payload
            for orders in account.orders_active.values():
                for (venue, symbol), order in orders.items():
                    payload = order.payload
                    payload.update(venue = venue, symbol = symbol, account = account.id)
                    df_orders[order.UID] = payload
            for trades in account.trades_closed.values():
                for (venue, symbol), trade in trades.items():
                    payload = trade.payload
                    payload.update(venue = venue, symbol = symbol, account = account.id)
                    df_trades[trade.UID] = payload
            for trades in account.trades_active.values():
                for (venue, symbol), trade in trades.items():
                    payload = trade.payload
                    payload.update(venue = venue, symbol = symbol, account = account.id)
                    df_trades[trade.UID] = payload

        df_account = DataFrame(self.account_hist)
        df_orders = DataFrame.from_dict(df_orders, orient = "index")
        df_trades = DataFrame.from_dict(df_trades, orient = "index")
        df_account = df_account.set_index(["id", "time"]).sort_index()
        df_account.to_csv(f"{_FOLDER_LOG}/{self.stream_prefix}_accs.csv")
        df_orders.to_csv(f"{_FOLDER_LOG}/{self.stream_prefix}_orders.csv")
        df_trades.to_csv(f"{_FOLDER_LOG}/{self.stream_prefix}_trades.csv")

#███████████████████████████████████████████████████████████████████████████████████████████████
#▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀